language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - ./create_config.sh
env:
  global:
    - secure: KRKTbYc7InVj55f7P8kJcJJcwuxgjXUBI2e0K4JuLazkv4N9xXeBhSbN8Hrgli3ViZtEexfbX4CqXrVcROD2Ur8visQiUzMWRZthR+zE0sbG/zc8wsy0egBYtExgtTA8Afx10hyut9pYpmgvZ55BV6a38fLTrbX/WJWO/ENRBik=
    - secure: dhHJeY8qmi0+aIQwfqcKGtLQn0Byjvd62QvkpWstwbsOQD14Pc+vUXR5thiHl1pBndLI6APe+Ka9myx50SnoZBnrO/c9dAIuaTVI+D7g2ews+eNKP0LJJEm8qs7jAx8RgN4ozuTZiUu37YR4pXQ4W6nJX8rK7VuBRJyVutNQonA=
    - secure: Capq7BeBRQuKifS3u/IdJr/zH9I8KrypuTdhoJHCRCKwGPAEzVqURdWltnx1TU+OdZ/lQW/ArWiLG+y74QSeMNGKoJkKsv3zTScme0JDgavPUC4rNQwMTUqPeoVAOjW5x1qikW4uIJ2bSqyUL5xJpOhElD/YkOQPuXaTEwpYOoQ=
    - secure: Fu4L057bM28hmUhsaZ1MmZ+5iAg9Pi6uX+xc40h2tRUGmb6DZNtnXye336EH2qtZQHLHBIGyab+ok9j2UQPW4wvFE+F2/ViR8NwBGmYgCZOy8xZiIBTZPjJbHqmmldpzSV47Pzv9HVk+h2+KXIfg4vikhnky9W+TOnMrpwYDUZ0=
    - secure: P41BCcGpYHHiqCoA6axG8q9iVQzS/iT9LkicE0gII60QrvOzouuXzift+Tljlmte05ZUaHHZ0cUxrkAsJye0tblMxkijNoL+Sjp8qjibEI9HunyB30ladKWCbAa+Cs5nb/bwP/HBkKnq3JjMPGbk+QY9D6EstwSu82ZBV/MOhMY=
    - secure: cAPGk5a5ue0a63DXtiD0jtWanyhGo1h2mRa+oot3ex6BGrDgMynTeWgvcKr9ojoN1LEpYeAOZpY6JXuvrtZ+IbP6dsDlot8D6ODzrjRympWkGZsObiTeQLz3v9hnGnXLq3cpT2IM1tsWkRbS4GyGMTDKK1X9E7aEO66eYTQjBcg=
notifications:
  hipchat:
    rooms:
      - secure: guX/XFau2x7arLvJPJiNF4KuGfS/LrxRPCLYrAlClKsSfSUUfrV7T6bs6dWBl6qWnJDDwWNBFnYcGqKl+nKYMtfNnMVPst9mgL/uM+bkR9eLjMPyPZ36JL/AVoC19INZDhQDEcnOLjyL40jUXsI5UyU0PjHQPi9lK2OwV1jf5AM=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a> / <a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: always
